# Site settings
title: Bitmap Wire Logic Simulator
email: 2139007+iaaa@users.noreply.github.com
description: A simple and visual bitmap simulation of a real 8-bit microprocessor to explain the very low-level principles of operation (lower than assembler).
baseurl: "/wire-logic"
url: "http://iaaa.github.io"
host: 0.0.0.0

exclude:
  - "src/"
  - "*.jade"
  - Makefile
  - README.md

# Build settings
markdown: kramdown
